mcserverslive/accounts/urls.py
from django.conf.urls import patterns, url
from accounts.views import *

urlpatterns = patterns('',

	url(r'^register/$', CustomRegistrationView.as_view(), name='register'),
	url(r'^email_settings/(?P<pk>\d+)/$', EmailSettingsUpdateView.as_view(), name='email_settings'),
	url(r'^email_settings/$', EmailSettingsUpdateView.as_view(), name='email_settings'),
)

mcserverslive/mcserverslive/urls.py
from django.conf.urls import patterns, include, url
from django.views.decorators.http import require_POST
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()

from mcserverslive.views import *

urlpatterns = patterns('',

	url(r'^$', ServerListView.as_view(), name='home'),
	url(r'^(?P<pk>\d+)/$', ServerDetailView.as_view(), name='detail'),
	url(r'^server_comments/(?P<pk>\d+)/$', ServerCommentListView.as_view(), name='server_comments'),
	url(r'my_servers/$', MyServerListView.as_view(), name='my_list'),
	url(r'server_create_form/$', ServerCreateView.as_view(), name='create'),
	url(r'server_update_form/(?P<pk>\d+)/$', ServerUpdateView.as_view(), name='update'),
	url(r'^server_delete/(?P<pk>\d+)/$', ServerDeleteView.as_view(), name='delete'),
	url(r'^server_comment_form/(?P<pk>\d+)/$', ServerCommentCreateView.as_view(), name='server_add_comment'),
	url(r'^donate/$', TemplateView.as_view(template_name='donate.html'), name='donate'),

	url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),

	url(r'^accounts/', include('accounts.urls',namespace='accounts')),
	url(r'^accounts/', include('registration.backends.default.urls')),
	url(r'^accounts/', include('django.contrib.auth.urls')),
#	url(r'^summernote/', include('django_summernote.urls')),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.ADMIN_ENABLED:
	urlpatterns += patterns('', url(r'^admin/', include(admin.site.urls)), )

mcserverslive/mcserverslive/models.py
from django.db import models
from django.contrib.auth.models import User
from mcserverslive.formatChecker import ContentTypeRestrictedFileField

####################
# Server model #####
####################

class Server(models.Model):

	user = models.ForeignKey(User)
	server_name = models.CharField(max_length = 40)
	ip = models.CharField(max_length = 50, blank=False)
	port = models.PositiveSmallIntegerField(default=25565, null=False) #query-port

	banner = ContentTypeRestrictedFileField(upload_to=".", 
		content_types=['image/gif', 'image/jpeg', 'image/png',], max_upload_size=5242880)

	host_port = models.PositiveSmallIntegerField(default=25565, null=True)
	motd = models.CharField(max_length = 100, null=True)
	version = models.CharField(max_length = 5, null=True)
	max_players = models.PositiveSmallIntegerField(null=True)
	game_type = models.CharField(max_length = 10, null=True) # are these choices? origin?
	website = models.URLField(blank=True)
	description = models.CharField(max_length=2000)
	votes = models.PositiveSmallIntegerField(default=0)

	class Meta:
		unique_together = (('ip','port'),) #query-port

	def __unicode__(self):
		return unicode(self.server_name)

##################
# Plugin #########
##################

class Plugin(models.Model):

	server = models.ForeignKey(Server)
	plugin = models.CharField(max_length = 50)

	def __unicode__(self):
		return unicode(self.plugin)

#######################
# Number of Players ###
#######################

class NumPlayers(models.Model):

	server = models.ForeignKey(Server)
	query_time = models.DateTimeField()
	num_players = models.PositiveSmallIntegerField(null=True)

	def __unicode__(self):
		return unicode(self.query_time)

##############################
# Long-term Archive Temporal #
##############################

class ArchiveNumPlayers(models.Model):
	
	server = models.ForeignKey(Server)
	query_time = models.DateTimeField()
	num_players = models.PositiveSmallIntegerField(null=True)

	def __unicode__(self):
		return unicode(self.query_time)

#########################
# Server Comment ########
#########################

class ServerComment(models.Model):

	server = models.ForeignKey(Server)
	comment_time = models.DateTimeField()
	user = models.ForeignKey(User)
	comment = models.CharField(max_length=300)	

	def __unicode__(self):
		return unicode(self.comment_time)	

mcserverslive/mcserverslive/forms.py
from django.forms import ModelForm, Form, ValidationError, Textarea, CharField, HiddenInput, ChoiceField, Select
from django.core.files.images import get_image_dimensions
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User

from mcserverslive.models import Server, ServerComment
from mcstatus.minecraft_query import MinecraftQuery
from accounts.pytz_choices import PYTZ_CHOICES
#from django_summernote.widgets import SummernoteInplaceWidget

###########################
# Server Update Form ######
###########################

class ServerUpdateForm(ModelForm):
	full_status = {}

	class Meta:
		model = Server
		fields = ['server_name','banner','description','website']
		widgets = { 'description': Textarea(attrs={'onKeyUp': "textCounter(this,'counter_description',2000);" } )}

	def clean(self):
		cleaned_data = super(ServerUpdateForm, self).clean()

		width, height = get_image_dimensions(cleaned_data['banner'])
		if width is not 560 and height is not 100:
			raise ValidationError(u'Banners need to be 560x100 pixels. Please resize image.')

		return cleaned_data

############################
# Server Create Form #######
############################

class ServerCreateForm(ModelForm):
	rand_motd = CharField(widget=HiddenInput())

	class Meta:
		model = Server
		fields = ['server_name','banner','ip','port','description','website']
		widgets = { 'description': Textarea(attrs={'onKeyUp': "textCounter(this,'counter_description',2000);"} )}

	def clean(self):

		cleaned_data = super(ServerCreateForm, self).clean()
		query = MinecraftQuery(cleaned_data['ip'], cleaned_data['port'])

		try:
			self.full_status = query.get_rules()
		except:
			raise ValidationError(u'Cannot query server. Is server.properties enable-query true?')

		if self.full_status['motd'] != cleaned_data['rand_motd']:
			raise ValidationError(u'Check that your server was reloaded with the random MOTD')

		return cleaned_data

	def clean_banner(self):
		data = self.cleaned_data['banner']
		width, height = get_image_dimensions(data)
		if width is not 560 and height is not 100:
			raise ValidationError(u'Banners need to be 560x100 pixels. Please resize image.')
		return data

	def save(self, commit=True):
		instance = super(ServerCreateForm, self).save(commit=False)
		instance.motd = self.full_status['motd']
		instance.version = self.full_status['version']
		instance.max_players = self.full_status['maxplayers']
		instance.game_type = self.full_status['gametype']
		instance.host_port = self.full_status['hostport']

		if commit:
			instance.save()

		right_now = timezone.now()
		num_players=self.full_status['numplayers']
		instance.numplayers_set.create(query_time = right_now, num_players = num_players)
		instance.archivenumplayers_set.create(query_time = right_now, num_players = num_players)	

		plugins = self.full_status['plugins']
		
		for plugin in plugins:
			instance.plugin_set.create(plugin=plugin)

		instance.servercomment_set.create(
			comment_time = right_now, user=User.objects.get(pk=1), comment = u'Welcome to the site!') 

		return instance

############################
# Server Comment Form ######
############################

class ServerCommentForm(ModelForm):
	
	class Meta:
		model = ServerComment
		fields = ['comment']
		widgets = { 'comment': Textarea(attrs={'onKeyUp': "textCounter(this,'counter_description',300);"}), }

	def clean_comment(self):
		data = self.cleaned_data['comment']
		words = data.split()
		for word in words:
			if len(word) > 60:
				raise ValidationError(u'No words more than 60 characters')
		return data
			
	def save(self, commit=True):
		instance = super(ServerCommentForm, self).save(commit=False)
		instance.comment_time = timezone.now()
		if commit:
			instance.save()
		return instance

##################################
# timezone select flot ###########
##################################

class TimezoneForm(Form):
	timezone = CharField(widget=Select(choices=PYTZ_CHOICES))

	def __init__(self, timezone, *args, **kwargs):
		super(TimezoneForm, self).__init__(*args, **kwargs)
		self.fields['timezone'].initial = timezone

mcserverslive/mcserverslive/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View 
from django.views.generic.edit import FormMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.forms import ValidationError
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, render_to_response
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.template import RequestContext

from datetime import timedelta
import random, string

from mcserverslive.models import *
from mcserverslive.forms import *
from accounts.models import UserProfile

#####################################
# Server List View ##################
#####################################

class ServerListView(ListView):
	model = Server
	paginate_by = 20

	def get_context_data(self, **kwargs):
		context = super(ServerListView, self).get_context_data(**kwargs)
		object_list = context['object_list']
		object_tuples = []
		for obj in object_list:
			num_players = obj.numplayers_set.all().latest('query_time')
			right_now = timezone.now()
			if num_players:	
				seconds = (right_now - num_players.query_time).total_seconds()
			else:
				num_players = self.get_object().archivenumplayers_set.all().latest('query_time')
				seconds = (right_now - num_players.query_time).total_seconds()			
			dt = int((seconds % 3600) // 60)
			np = num_players.num_players
			object_tuples.append((obj, dt, np))			
		context['object_tuples'] = object_tuples
		return context

	def get_queryset(self):
		return Server.objects.all().order_by('-votes')

##########################################
# User Server List View ##################
##########################################

class MyServerListView(ListView):
	template_name = 'mcserverslive/my_server_list.html'
	model = Server
	paginate_by = 20

	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(MyServerListView, self).dispatch(*args, **kwargs)

	def get_queryset(self):
		return Server.objects.filter(user=self.request.user).order_by('-votes')

####################################
# Create a Server Listing ##########
####################################

class ServerCreateView(CreateView):
	form_class = ServerCreateForm
	template_name = 'server_add_form.html'

	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(ServerCreateView, self).dispatch(*args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super(ServerCreateView, self).get_context_data(**kwargs)
		context['rand_motd'] = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(15))
		return context

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super(ServerCreateView, self).form_valid(form)

	def get_success_url(self):
		return reverse('my_list')


##################################
# Update a Server Listing ########
##################################

class ServerUpdateView(UpdateView):
	form_class = ServerUpdateForm
	template_name = 'server_update_form.html'
	model = Server

	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		if self.request.user == self.get_object().user:
			return super(ServerUpdateView, self).dispatch(*args, **kwargs)
		else:
			return HttpResponseForbidden('<h1>403 Forbidden</h1><p>Please only update your own posts.</p>')

	def get_success_url(self):
		return reverse('detail', kwargs={'pk': self.kwargs['pk']})

#################################
# Delete a Listing ##############
#################################

class ServerDeleteView(DeleteView):
	model = Server
	template_name = 'server_confirm_delete.html'
	
	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		if self.request.user == self.get_object().user:
			return super(ServerDeleteView, self).dispatch(*args, **kwargs)
		else:
			return HttpResponseForbidden('<h1>403 Forbidden</h1><p>Please only delete your own posts.</p>')

	def get_success_url(self):
		return reverse('my_list')

#################################
# Server Detail  ################
#################################

class ServerDetailView(FormMixin, DetailView):
	model = Server
	form_class = TimezoneForm

	def get_form_kwargs(self):
		kwargs = super(ServerDetailView, self).get_form_kwargs()
		if self.request.user.is_authenticated():
			timezone = get_object_or_404(User, pk=self.request.user.pk).userprofile.timezone
		else:
			timezone = 'US/Eastern'
		kwargs['timezone'] = timezone
		return kwargs

	def get_context_data(self, **kwargs):
		context = super(ServerDetailView, self).get_context_data(**kwargs)
		form_class = self.get_form_class()
		context['form'] = self.get_form(form_class)
		return context

######################################
# Comment List View ##################
######################################

class ServerCommentListView(ListView):
	model = ServerComment
	paginate_by = 30
	template_name = 'server_list.html'

	def get_queryset(self):
		return ServerComment.objects.filter(server = self.kwargs['pk']).order_by('-comment_time')

	def get_context_data(self, **kwargs):
		context = super(ServerCommentListView, self).get_context_data(**kwargs)
		context['server'] = self.object_list[0].server
		return context

#############################
# Comment Create View #######
#############################

class ServerCommentCreateView(CreateView):
	form_class = ServerCommentForm
	template_name = 'server_comment_form.html'

	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(ServerCommentCreateView, self).dispatch(*args, **kwargs)

	def form_valid(self, form):
		form.instance.user = self.request.user
		form.instance.server = get_object_or_404(Server,id=self.kwargs['pk'])
		return super(ServerCommentCreateView, self).form_valid(form)

	def get_context_data(self, **kwargs):
		context = super(ServerCommentCreateView, self).get_context_data(**kwargs)
		context['server'] = get_object_or_404(Server, id=self.kwargs['pk'])
		return context

	def get_success_url(self):
		return reverse('detail', kwargs={'pk': self.kwargs['pk']})

mcserverslive/mcserverslive/templates/base.html
<!DOCTYPE html>
<html  lang="en">

{% load staticfiles %}
{% load dajaxice_templatetags %}

<head>

	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" type="image/ico" href="{% static "mcserverslive/images/favicon.ico" %}" />
	{% block description %}{% endblock %}
	<title>{% block title %}{% endblock %}</title>

	<link rel="stylesheet" href="{% static "bootstrap-3.2.0-dist/css/bootstrap.min.css" %}" />
	<link rel="stylesheet" href="{% static "bootstrap-3.2.0-dist/css/bootstrap-theme.min.css" %}" />
	<link rel="stylesheet" href="{% static "slider/css/slider.css" %}" />
	<link rel="stylesheet" href="{% static "mcserverslive/css/main.css" %}" />

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src="{% static "bootstrap-3.2.0-dist/js/bootstrap.min.js" %}"></script>
	{% dajaxice_js_import %}
	<script language="javascript" type="text/javascript" src="{% static "mcserverslive/js/functions.js" %}"></script>

</head>

<body>

		{% include 'nav.html' %}

		<div class="container" style="margin-top: 10%; margin-bottom: 5%;">
			{% block content %}{% endblock %}
		</div>

		{% block footer %}{% endblock %}

</body>

</html>

mcserverslive/mcserverslive/templates/footer.html
<div class="footer">
	<div class="container">
		<p class="text-muted">mcserverslive.com &copy; 2014. mcserverslive.com is not associated with Mojang. For support contact <a href="mailto:support@mcserverslive.com">support@mcserverslive.com</a>
		</p>
	</div>
</div>

mcserverslive/mcserverslive/templates/form_errors.html
	{% if form.non_field_errors %}
		<div class="alert alert-warning" role="alert">
			{{ form.non_field_errors }}
		</div>
	{% endif %}
	{% if form.errors %}
		<div class="alert alert-warning" role="alert">
			{{ form.errors }}
		</div>
	{% endif %}

mcserverslive/mcserverslive/templates/lockout.html
{% extends "base.html" %}

{% block title %}Lockout Notification{% endblock %}

{% block content %}
<div class="page-header">
	<h1>mcserverslive</h1>
	<p class="lead">Lockout Notification</p>
</div>

<h2 class="sub-header">You are currently locked out</h2>
<div style="margin: 10%;">
	You attempted to login {{ failure_limit }} times, unsuccessfully. Please email support@{{ domain }} to request a reset.
</div>

<script>

$(function() {
	// add active class to nav
	$("a:contains('Login')").parent().addClass("active");
});

</script>
{% endblock %}

mcserverslive/mcserverslive/templates/nav.html
{% load staticfiles %}

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">mcserverslive</a>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class=""><a href="{% url 'home' %}">Minecraft Server List</a></li>
				
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">My Account<span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li class=""><a href="{% url 'my_list' %}">My Servers</a></li>
							<li class=""><a href="{% url 'auth_password_change' %}">Change Password</a></li>
							{% if user.is_authenticated %}
							<li class=""><a href="{% url 'accounts:email_settings' user.pk %}">Email Settings</a></li>
							{% else %}
							<li class=""><a href="{% url 'accounts:email_settings' %}">Email Settings</a></li>
							{% endif %}
						</ul>
					</li>
				
				<li class=""><a href="{% url 'create' %}">Add a Server</a></li>
				<li class=""><a href="{% url 'donate' %}">Donate</a></li>
				{% if user.is_authenticated %}
					<li class=""><a href="{% url 'logout' %}">{{ user }} Logout</a></li>
				{% else %}
					<li class=""><a href="{% url 'login' %}">Login/Register</a></li>
				{% endif %}
			</ul>
		</div>
	</div>
</div>

mcserverslive/mcserverslive/templates/pagination.html
{% load staticfiles %}

	<div class="pagination">

			{% if page_obj.has_previous %}
				<a href="?page={{ page_obj.previous_page_number }}">previous</a>
			{% else %}
				previous
			{% endif %}

			&lt;&lt; Page {{ page_obj.number }} of {{ paginator.num_pages }} &gt;&gt;
			
			{% if page_obj.has_next %}
				<a href="?page={{ page_obj.next_page_number }}">next</a>
			{% else %}
				next
			{% endif %}

	</div>

mcserverslive/mcserverslive/templates/server_add_form.html
{% extends "base.html" %}

{% block title %}List a Minecraft Servers{% endblock %}

{% block description %}
<meta name="description" content="List a Minecraft Servers" />
{% endblock %}

{% block content %}

<div class="page-header">
	<h1>Add a Minecraft Server Listing</h1>
	<p class="lead">Reload your server with the following MOTD to add. You can change this after your server is listed.</p>
	<p class="lead">{{ rand_motd }}</p>
</div>

<form class="my-form" enctype="multipart/form-data" action="" method="post">{% csrf_token %}
	{% include 'form_errors.html' %}
	{{ form.server_name }}
	{{ form.website }}
	{{ form.banner.label }}<div>(Must be 560x100 pixels)</div>
	{{ form.banner }}
	{{ form.ip }}
	{{ form.port }}

		{% comment %}<div id="description_used"></div>{% endcomment %}

	<div id="counter_description">Maximum characters: 2000</div>
	{{ form.description }}
	<button class="btn btn-lg btn-success btn-block" type="submit"/>Add</button>
	<input type="hidden" name="rand_motd" value="{{ rand_motd }}" />
</form>	

<script>

//function summernoteCounter(){
//	var max_chars = 2000;
//	var html_char_count = $('.note-editable').code().length;
//	var percent_remaining = Math.round(100*(max_chars-html_char_count)/max_chars);
//	var counter_string = "Description unused: " + percent_remaining.toString() + "%";
//	$("#description_used").html(counter_string);
//}

$(function() {
	$("a:contains('Add')").parent().addClass("active");
	$("input[name=server_name]").addClass("form-control");
	$("input[name=server_name]").attr("placeholder", "Server Name");
	$("input[name=ip]").addClass("form-control");
	$("input[name=ip]").attr("placeholder", "IP");
	$("input[name=port]").addClass("form-control");
	$("input[name=port]").attr("style", "margin-bottom: 3%;");
	$("input[name=website]").addClass("form-control");
	$("input[name=website]").attr("placeholder", "Website (optional)");
	$("input[name=website]").attr("style","margin-bottom: 5%;");
	$("input[name=banner]").addClass("form-control");

	$("textarea[name=description]").addClass("form-control");
	$("textarea[name=description]").attr("placeholder", "Description");

//	summernoteCounter();
//	$("div[class=note-editable], button").on('keyup focus blur paste init change click', function(){
//		summernoteCounter();
//	});

});

</script>

{% endblock %}

mcserverslive/mcserverslive/templates/server_comment_form.html
{% extends "base.html" %}

{% block title %}Comment on {{ server.server_name }}{% endblock %}

{% block description %}
<meta name="description" content="Comment on {{ server.server_name }}" />
{% endblock %}

{% block content %}

<div class="page-header">
	<h1>Post a comment</h1>
	<p class="lead">about {{ server.server_name }}</p>
</div>

<form class="my-form" method="post" action="">{% csrf_token %}
	{% include 'form_errors.html' %}	
	<div id="counter_description">Maximum characters: 300</div>
	{{ form.comment }}
	<button class="btn btn-lg btn-success btn-block" type="submit"/>Post</button>
</form>

<script>

$(function() {
	$("textarea[name=comment]").addClass("form-control");
	$("textarea[name=comment]").attr("placeholder", "Description");
});

</script>

{% endblock %}

mcserverslive/mcserverslive/templates/server_confirm_delete.html
{% extends "base.html" %}

{% block title %}Server Form{% endblock %}

{% block content %}

<div class="page-heading">
	<h1>Delete Confirm</h1>
	<p class="lead">Are you sure you want to delete "{{ object }}"?</p>
	<p class="lead">It DELETES ALL of our data associated with it.</p>
</div>

<form action="" method="post">{% csrf_token %}
    <button class="btn btn-lg btn-danger" type="submit"/>Confirm DELETE</button>
</form>

{% endblock %}

mcserverslive/mcserverslive/templates/server_update_form.html
{% extends "base.html" %}

{% block title %}Minecraft Server Update{% endblock %}

{% block description %}
<meta name="description" content="Minecraft Server Update" />
{% endblock %}

{% block content %}

<div class="page-header">
	<h1>Update a Server Listing</h1>
</div>

<form class="my-form" enctype="multipart/form-data" action="" method="post">{% csrf_token %}
	{% include 'form_errors.html' %}
	{{ form.server_name }}
	{{ form.website }}
	{{ form.banner.label }}
	<div>(Must be 560x100 pixels)</div>
	{{ form.banner }}

		{% comment %}<div id="description_used"></div>{% endcomment %}

	<div id="counter_description">Maximum characters: 2000</div>
	{{ form.description }}
	<button class="btn btn-lg btn-success btn-block" type="submit"/>Update</button>
</form>

<script>

//function summernoteCounter(){
//	var max_chars = 2000;
//	var html_char_count = $('.note-editable').code().length;
//	var percent_remaining = Math.round(100*(max_chars-html_char_count)/max_chars);
//	var counter_string = "Description unused: " + percent_remaining.toString() + "%";
//	$("#description_used").html(counter_string);
//}

$(function() {
	
	$("a:contains('Account')").parent().addClass("active");
	$("input[name=server_name]").addClass("form-control");
	$("input[name=server_name]").attr("placeholder", "Server Name");
	$("input[name=website]").addClass("form-control");
	$("input[name=website]").attr("placeholder", "Website (optional)");
	$("input[name=website]").attr("style","margin-bottom: 5%;");
	$("input[name=banner]").addClass("form-control");

	$("textarea[name=description]").addClass("form-control");
	$("textarea[name=description]").attr("placeholder", "Description");
	
//	summernoteCounter();
//	$("div[class=note-editable], button").on('keyup focus blur paste init change click', function(){
//		summernoteCounter();
//	});

});

</script>
{% endblock %}

mcserverslive/mcserverslive/templates/servercomment_list_item.html
<div class="row" style="margin-bottom: 1%;">
	<div class="col-md-4" style="clear: both;">
		{{ comment.user }}
	</div>
	<div class="col-md-8">
		{{ comment.comment_time }}<br /><br/>
		{{ comment.comment }}
	</div>	
</div><hr />

mcserverslive/mcserverslive/templates/summernote_scripts.html
	<script src="/static/django_summernote/jquery.ui.widget.js" type="text/javascript"></script>
	<script src="/static/django_summernote/jquery.iframe-transport.js" type="text/javascript"></script>
	<script src="/static/django_summernote/jquery.fileupload.js" type="text/javascript"></script>
	<script src="/static/django_summernote/summernote.min.js" type="text/javascript"></script>